// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzfc7yOPXZ6n1AJg8iHipgpzgLPLFUuj0',
    appId: '1:232920202136:web:0a9bc1944e0ce32889c9ed',
    messagingSenderId: '232920202136',
    projectId: 'todolist-27d47',
    authDomain: 'todolist-27d47.firebaseapp.com',
    storageBucket: 'todolist-27d47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPalF2w-yyHubs2mG2p1BnW2q53G89JhU',
    appId: '1:232920202136:android:72b65b2d8b86af4c89c9ed',
    messagingSenderId: '232920202136',
    projectId: 'todolist-27d47',
    storageBucket: 'todolist-27d47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbulgFsh12DFBc89KsrxSfv-k4abPs2gc',
    appId: '1:232920202136:ios:041dc9bd98baffa389c9ed',
    messagingSenderId: '232920202136',
    projectId: 'todolist-27d47',
    storageBucket: 'todolist-27d47.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbulgFsh12DFBc89KsrxSfv-k4abPs2gc',
    appId: '1:232920202136:ios:041dc9bd98baffa389c9ed',
    messagingSenderId: '232920202136',
    projectId: 'todolist-27d47',
    storageBucket: 'todolist-27d47.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzfc7yOPXZ6n1AJg8iHipgpzgLPLFUuj0',
    appId: '1:232920202136:web:edf9a734a805e5d289c9ed',
    messagingSenderId: '232920202136',
    projectId: 'todolist-27d47',
    authDomain: 'todolist-27d47.firebaseapp.com',
    storageBucket: 'todolist-27d47.appspot.com',
  );
}
